[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "enrich idea flame palace matrix rail story industry stadium fitness sadness pulse tomato patrol roof crystal width vast father melt left chronic hand arena"
